if (self.CavalryLogger) { CavalryLogger.start_js(["6NQ69"]); }

__d("CometVideoHomeCatalogRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3277542982280458",metadata:{relayPreloadable:!0},name:"CometVideoHomeCatalogRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideoHomeLatestRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3090235894393665",metadata:{relayPreloadable:!0},name:"CometVideoHomeLatestRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideoHomeSavedRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3086532008071897",metadata:{relayPreloadable:!0},name:"CometVideoHomeSavedRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideoHomeUpdatesSurfaceRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3635888436427858",metadata:{relayPreloadable:!0},name:"CometVideoHomeUpdatesSurfaceRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideoHomeCatalogRoot.entrypoint",["JSResource","WebPixelRatio","buildCometVideoHomeRoute.entrypoint","qex","CometVideoHomeCatalogRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";e.exports=b("buildCometVideoHomeRoute.entrypoint")(b("JSResource")("CometVideoHomeCatalogRoot.react").__setRef("CometVideoHomeCatalogRoot.entrypoint"),function(a){return{queries:{catalogRootQueryReference:{parameters:b("CometVideoHomeCatalogRootQuery$Parameters"),variables:{feedHeroEnabled:!!b("qex")._("1418988"),scale:b("WebPixelRatio").get()}}}}})}),null);
__d("CometVideoHomeLatestRoot.entrypoint",["JSResource","WebPixelRatio","buildCometVideoHomeRoute.entrypoint","qex","CometVideoHomeLatestRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";e.exports=b("buildCometVideoHomeRoute.entrypoint")(b("JSResource")("CometVideoHomeLatestRoot.react").__setRef("CometVideoHomeLatestRoot.entrypoint"),function(a){return{queries:{latestRootQueryReference:{parameters:b("CometVideoHomeLatestRootQuery$Parameters"),variables:{feedHeroEnabled:!!b("qex")._("1418988"),scale:b("WebPixelRatio").get()}}}}})}),null);
__d("CometVideoHomeSavedRoot.entrypoint",["JSResource","WebPixelRatio","buildCometVideoHomeRoute.entrypoint","qex","CometVideoHomeSavedRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";e.exports=b("buildCometVideoHomeRoute.entrypoint")(b("JSResource")("CometVideoHomeSavedRoot.react").__setRef("CometVideoHomeSavedRoot.entrypoint"),function(a){return{queries:{savedRootQueryReference:{parameters:b("CometVideoHomeSavedRootQuery$Parameters"),variables:{feedHeroEnabled:!!b("qex")._("1418988"),scale:b("WebPixelRatio").get()}}}}})}),null);
__d("CometVideoHomeUpdatesSurfaceEntryPointVariables",["CometVideoHomeCommonEntryPointVariables","qex"],(function(a,b,c,d,e,f){"use strict";a=babelHelpers["extends"]({},b("CometVideoHomeCommonEntryPointVariables"),{feedHeroEnabled:!!b("qex")._("1418988")});e.exports=a}),null);
__d("CometVideoHomeUpdatesSurfaceRoot.entrypoint",["CometVideoHomeUpdatesSurfaceEntryPointVariables","JSResource","buildCometVideoHomeRoute.entrypoint","CometVideoHomeUpdatesSurfaceRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";e.exports=b("buildCometVideoHomeRoute.entrypoint")(b("JSResource")("CometVideoHomeUpdatesSurfaceRoot.react").__setRef("CometVideoHomeUpdatesSurfaceRoot.entrypoint"),function(a){return{queries:{updatesSurfaceRootQueryReference:{parameters:b("CometVideoHomeUpdatesSurfaceRootQuery$Parameters"),variables:b("CometVideoHomeUpdatesSurfaceEntryPointVariables")}}}})}),null);