if (self.CavalryLogger) { CavalryLogger.start_js(["mjCp7"]); }

__d("CoronavirusCometRootContentQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3093980820647057",metadata:{relayPreloadable:!0},name:"CoronavirusCometRootContentQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CoronavirusHubCometRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3057913624327349",metadata:{relayPreloadable:!0},name:"CoronavirusHubCometRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CoronavirusCometHeaderQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3169573863074007",metadata:{relayPreloadable:!0},name:"CoronavirusCometHeaderQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideoHomeLiveRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3260296407367775",metadata:{relayPreloadable:!0},name:"CometVideoHomeLiveRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("buildCoronavirusCometRoot.entrypoint",["JSResource","createContentAreaCompoundEntryPointBuilder","CoronavirusCometRootContentQuery$Parameters","CoronavirusCometHeaderQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";e.exports=b("createContentAreaCompoundEntryPointBuilder")(b("JSResource")("CoronavirusCometRoot.react").__setRef("buildCoronavirusCometRoot.entrypoint"),function(a){return{crisisQueryReference:{parameters:b("CoronavirusCometRootContentQuery$Parameters"),variables:{}},headerQueryReference:{parameters:b("CoronavirusCometHeaderQuery$Parameters"),variables:{}}}})}),null);
__d("CoronavirusHubCometRoot.entrypoint",["JSResource","WebPixelRatio","buildCoronavirusCometRoot.entrypoint","CoronavirusHubCometRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";e.exports=b("buildCoronavirusCometRoot.entrypoint")(b("JSResource")("CoronavirusHubCometRoot.react").__setRef("CoronavirusHubCometRoot.entrypoint"),function(a){return{queries:{queryReference:{parameters:b("CoronavirusHubCometRootQuery$Parameters"),variables:{UFI2CommentsProvider_commentsKey:"CoronavirusHubCometRootQuery",containerIsFeedStory:!0,containerIsLiveStory:!1,containerIsTahoe:!1,containerIsWorkplace:!1,displayCommentsContextEnableComment:!0,displayCommentsContextIsAdPreview:!1,displayCommentsContextIsAggregatedShare:!1,displayCommentsContextIsStorySet:!1,displayCommentsFeedbackContext:null,feedLocation:"COMET_CORONAVIRUS_HUB_FEED",feedbackSource:22,focusCommentID:null,isComet:!0,privacySelectorRenderLocation:"COMET_CORONAVIRUS_HUB",renderLocation:"coronavirus_hub_feed",scale:b("WebPixelRatio").get(),useDefaultActor:!1}}}}})}),null);
__d("CometVideoHomeLiveEntryPointVariables",["WebPixelRatio","gkx","qex"],(function(a,b,c,d,e,f){"use strict";a={disableCometFullWidthHero:!!b("qex")._("1425792"),scale:b("WebPixelRatio").get(),useCometLiveEndedOverlay:b("gkx")("1362110")};c=!!b("qex")._("1425793");d=!1;f=!1;var g=!0;c&&(d=b("gkx")("1365892"),f=!!b("qex")._("1107866"),g=b("gkx")("1344274"));c={containerIsFeedStory:!0,containerIsLiveStory:!0,containerIsTahoe:!1,containerIsWorkplace:!1,feedLocation:"VIDEO_HOME_LIVE_TAB",feedbackSource:60,heroUFIEnabled:c,isComet:b("gkx")("708253"),removeRealtimeUFI:g,shareSheetRedesign:d,useBlueDesign:f};g=babelHelpers["extends"]({},a,{isComet:b("gkx")("708253")});d=babelHelpers["extends"]({},a,c,{skipGridComponentAttachedStory:b("gkx")("1454794"),useThumbnailPreviewRelay3d:b("gkx")("1357994")});e.exports={CometVideoHomeLiveHeroEntryPointVariables:g,CometVideoHomeLiveHeroUFIEntryPointVariables:c,CometVideoHomeLiveRootEntryPointVariables:d}}),null);
__d("CometVideoHomeLiveRoot.entrypoint",["CometVideoHomeLiveEntryPointVariables","JSResource","buildCometVideoHomeRoute.entrypoint","CometVideoHomeLiveRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";var g=b("CometVideoHomeLiveEntryPointVariables").CometVideoHomeLiveRootEntryPointVariables;e.exports=b("buildCometVideoHomeRoute.entrypoint")(b("JSResource")("CometVideoHomeLiveRoot.react").__setRef("CometVideoHomeLiveRoot.entrypoint"),function(a){return{queries:{liveRootQueryReference:{parameters:b("CometVideoHomeLiveRootQuery$Parameters"),variables:babelHelpers["extends"]({},g,{trigger_data:{injected_video_id:null}})}}}})}),null);