if (self.CavalryLogger) { CavalryLogger.start_js(["RAwUy"]); }

__d("CometAggregatedEntitiesTooltipRenderer_entities.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:{mask:!1},name:"CometAggregatedEntitiesTooltipRenderer_entities",selections:[{alias:null,args:null,kind:"ScalarField",name:"count",storageKey:null},{alias:null,args:null,concreteType:null,kind:"LinkedField",name:"sample_entities",plural:!0,selections:[{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null},{kind:"InlineFragment",selections:[{alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"name",storageKey:null}],type:"User",abstractKey:null}],storageKey:null}],type:"AggregatedEntitiesAtRange",abstractKey:null};e.exports=a}),null);
__d("CometImageEntityRenderer_entity.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:{mask:!1},name:"CometImageEntityRenderer_entity",selections:[{alias:null,args:null,concreteType:null,kind:"LinkedField",name:"entity_with_image",plural:!1,selections:[{alias:null,args:null,concreteType:"Image",kind:"LinkedField",name:"image",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"height",storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"scale",storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"uri",storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"width",storageKey:null}],storageKey:null}],storageKey:null}],type:"ImageAtRange",abstractKey:null};e.exports=a}),null);
__d("useCometPhotoViewerPlaceholderPassthroughProps_photo.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[{kind:"RootArgument",name:"scale",type:"Float"}],kind:"Fragment",metadata:null,name:"useCometPhotoViewerPlaceholderPassthroughProps_photo",selections:[{alias:"viewer_image",args:[{kind:"Literal",name:"context",value:"comet_media_viewer"},{kind:"Literal",name:"height",value:1e6},{kind:"Variable",name:"scale",variableName:"scale"},{kind:"Literal",name:"width",value:1e6}],concreteType:"Image",kind:"LinkedField",name:"image",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"height",storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"width",storageKey:null}],storageKey:null}],type:"Photo",abstractKey:null};e.exports=a}),null);
__d("CometAggregatedEntitiesTooltipRenderer",["fbt","CometRelay","CometTooltip.react","React","stylex","CometAggregatedEntitiesTooltipRenderer_entities.graphql"],(function(a,b,c,d,e,f,g){"use strict";var h;b("CometRelay").graphql;var i=b("React");h!==void 0?h:h=b("CometAggregatedEntitiesTooltipRenderer_entities.graphql");a=function(a,c){var d;d=(d=c.count)!=null?d:0;c=(c=c.sample_entities)!=null?c:[];d=d-c.length;var e=d>0;return i.jsx(b("CometTooltip.react"),{forceInlineDisplay:!0,tooltip:i.jsxs(i.Fragment,{children:[c.map(function(a){if(a.__typename!=="User")return null;var b=a.id;a=a.name;return b!=null&&a!=null?i.jsx("div",{children:a},b):null}),e?i.jsx("div",{children:g._("and {count} more...",[g._param("count",d)])}):null]}),children:i.jsx("span",{className:"lrazzd5p nhd2j8a9 oo9gr5id",children:a})})};e.exports=a}),null);
__d("CometImageEntityRenderer",["CometImage.react","CometRelay","React","stylex","CometImageEntityRenderer_entity.graphql"],(function(a,b,c,d,e,f){"use strict";var g,h;b("CometRelay").graphql;var i=b("React"),j={image:{display:"q9uorilb",marginEnd:"cgat1ltu",verticalAlign:"ljoqfudb"}};g!==void 0?g:g=b("CometImageEntityRenderer_entity.graphql");a=function(a,c){c=(c=(c=c.entity_with_image)==null?void 0:c.image)!=null?c:{};var d=c.height,e=c.scale,f=c.uri;c=c.width;return d==null||f==null||c==null||e==null?a:i.jsx(b("CometImage.react"),{className:(h||(h=b("stylex")))(j.image),height:d/e,src:f,width:c/e})};e.exports=a}),null);
__d("CometFeedUnitQueryVariablesContext",["React"],(function(a,b,c,d,e,f){"use strict";a=b("React");c=a.createContext(null);e.exports=c}),null);
__d("CometFeedStoryAttachmentCommandWidget",["createKeyCommandWidget"],(function(a,b,c,d,e,f){"use strict";a=b("createKeyCommandWidget")();var g=a.useKeyCommands;a.useKeyCommands=function(a){g(a,!0)};e.exports=a}),null);
__d("useCometPhotoViewerPlaceholderPassthroughProps",["CometRelay","useCometPhotoViewerPlaceholderPassthroughProps_photo.graphql"],(function(a,b,c,d,e,f){"use strict";var g;b("CometRelay").graphql;var h=b("CometRelay").useFragment;function a(a){var c,d=a.photo;a=a.placeholderImageSrc;d=h(g!==void 0?g:g=b("useCometPhotoViewerPlaceholderPassthroughProps_photo.graphql"),d);return{origHeight:d==null?void 0:(c=d.viewer_image)==null?void 0:c.height,origSrc:a,origWidth:d==null?void 0:(c=d.viewer_image)==null?void 0:c.width}}e.exports=a}),null);